name: 'GE Experiment Report'
description: 'Experiment Report'
inputs:
  api-key:
    description: ""
    required: true
  url:
    description: ""
    required: true
  task:
    description: ""
    requierd: true
  max-builds:
    description: ""
    required: false
    default: 500  
  experiment-id:
    description: ""
    required: true
  tags:
    description: ""
    required: true
  project:
    description: ""
    required: true
  gh_token:
    description: ""
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11.0.4
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      id : geapix
      run: |
           pwd
           mkdir geapi
           cd geapi
           git clone https://github.com/cdsap/GradleEnterpriseApiReports.git
           cd GradleEnterpriseApiReports
           git checkout different_output_experiment
           #./gradlew install
           #process tags
           tags=${{ inputs.tags }}
           arrayTags=(${IN//,/ })
           tagsParsed=""
           for val in "${arrayTags[@]}";
           do
              tagsParsed="$tagsParsed --tags=$val"
           done

           #geapi/build/install/geapi/bin/geapi --help > alo
           echo "1" > alo
           #geapi/build/install/geapi/bin/geapi --report=experiment --experiment-output=file --url=https://ge.solutions-team.gradle.com  --task=${{ inputs.task }} --max-builds=${{ inputs.max-builds }}  $tagsParsed    --tags=experiment --tags=${{github.run_number}} --experiment-id=${{ inputs.experiment-id }} --project=${{ inputs.project }} --api-key=${{ inputs.api-key }}
           echo "1" > results_experiment.txt
           chmod 0757 results_experiment.txt
           ls -la
           pwd
           cd ..
           pwd
           ls -la
      shell: bash
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        path: geapi/GradleEnterpriseApiReports/results_experiment.txt
        if-no-files-found: error 