name: 'GE Experiment Report'
description: 'Experiment Report'
inputs:
  api-key:
    description: ""
    required: true
  url:
    description: ""
    required: true
  task:
    description: ""
    requierd: true
  max-builds:
    description: ""
    required: false
    default: 500  
  experiment-id:
    description: ""
    required: true
  tags:
    description: ""
    required: true
  project:
    description: ""
    required: true
  gh_token:
    description: ""
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11.0.4
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      id : geapix
      run: |
           mkdir geapi
           cd geapi
           git clone https://github.com/cdsap/GradleEnterpriseApiReports.git
           cd GradleEnterpriseApiReports
           git checkout main
           ./gradlew install
           #process tags
           tags=${{ inputs.tags }}
           arrayTags=(${IN//,/ })
           tagsParsed=""
           for val in "${arrayTags[@]}";
           do
              tagsParsed="$tagsParsed --tags=$val"
           done

           geapi/build/install/geapi/bin/geapi --help 
           geapi/build/install/geapi/bin/geapi --report=experiment --url=https://ge.solutions-team.gradle.com  --task=${{ inputs.task }} --max-builds=${{ inputs.max-builds }}  $tagsParsed    --tags=experiment --tags=${{github.run_number}} --experiment-id=${{ inputs.experiment-id }} --project=${{ inputs.project }} --api-key=${{ inputs.api-key }} > alo
           cat alo
      shell: bash
    - name: Send
      uses: actions/github-script@v5
      with:
        github-token: ${{inputs.gh_token}}
        script: |
                const fs = require('fs');

                fs.readFile('alo', 'utf8', (err, data) => {
                if (err) {
                  console.error(err);
                  return;
                }
                console.log(data);
                });
                
                const comment = 'LOL';
                github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: scriptS
                })


