name: Run Gradle on PRs
on: pull_request
jobs:
  temurin:
    strategy:
      matrix:
        java: [3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Execute Gradle build
        run: |
          sed -i "s/\$PRIVATE_KEY_ID/${{ secrets.BUCKET_PRIVATE_KEY_ID }}/" cache-node.json
          ./gradlew :build-logic:convention:compileKotlin -Dscan.tag.WORKERS${{ matrix.java }}-temurin
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          MAX_PARALLEL_FORKS: "3"
