name: Run Gradle on PRs
on: pull_request
jobs:
  temurin:
    strategy:
      matrix:
        java: [3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Execute Gradle build
        run: |
          ./gradlew  :core:model:compileKotlin -Dscan.tag.WORKERS${{ matrix.java }}-temurin
          cd .gradle/7.6
          ls
          cd dependencies-accessors
          ls -la
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          MAX_PARALLEL_FORKS: "${{ matrix.java }}"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          path: .gradle/*
          if-no-files-found: error

