on: [push]

jobs:
    example_matrix:
      strategy:
        matrix:
          version: [main, pr]
      runs-on: "ubuntu-latest"
      steps:
         - uses: actions/checkout@v3
         - id: foo
           uses: ./.github/actions/ge-experiment-runner
           with:
             task: "assembleDebug"
             experiment-id: ${{github.run_number}}
             variant: ${{ matrix.version }}
             class: "core/data/src/main/java/com/google/samples/apps/nowinandroid/core/data/repository/NewsRepository.kt"
             GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

