name: Run Gradle on PRs
on: pull_request
jobs:
  temurin:
    strategy:
      matrix:
        java: [1,2,3,4,5,6,7,8,9,10]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 11
        - name: Execute Gradle build
          run: ./gradlew test -Dscan.tag.WORKERS${{ matrix.java }}-temurin
          env:
            GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}
            MAX_PARALLEL_FORKS: "${{ matrix.java }}"
