name: Run Gradle on PRs
on: pull_request
jobs:
  temurin:
    strategy:
      matrix:
        java: [3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Execute Gradle build
        run: |
          ./gradlew :core:model:compileKotlin --info
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  liberica:
    strategy:
      matrix:
        java: [3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 11
      - name: Execute Gradle build
        run: |
          ./gradlew :core:model:compileKotlin --info
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
